name: CI

on:
  workflow_dispatch:
  issue_comment:
    types: [ created ]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  format:
    # Only run if either manually triggered or it was a comment strictly being '/format' in a PR
    if: ${{ !github.event.issue || (github.event.issue.pull_request && github.event.comment.body == '/format') }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout pull request
        if: ${{ github.event.issue.pull_request }}
        run: |
          gh pr checkout ${{ github.event.issue.number }}

      - name: Reformat code
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: "Core/"
          extensions: "c,h"
          clangFormatVersion: 17
          inplace: True

      - name: Check for changes
        id: check
        run: |
          if [ "$(git status --short)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        if: steps.check.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Reformat code"
          git push
